### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by mattgwwalker** [TeamPyOgg/PyOgg#43]
@Zuzu-Typ, I have set up basic continuous integration using Travis CI.  All the tests are passing for both a macOS and a Windows environment.

Do you have access to the Travis CI configuration?  Assuming you do, if you have the time, do you have any comments on the set up?  Would you do anything differently?

Cheers,

Matthew

**Comment by Zuzu-Typ** [comment]
I've updated the config to first test PyOgg and if it has a new version tag here on GitHub, it will build binaries for Windows, Linux and MacOS and upload them to GitHub and PyPI automatically.

I'm not sure if everything works as I would need to publish a new version to test it.
Time will tell (: 

Cheers
--Zuzu_Typ--
