### ISSUE TITLE
License details

### ISSUE THREAD

**Issue by mattgwwalker** [TeamPyOgg/PyOgg#52]
@Zuzu-Typ I see that you've added license details into the file `opus_file.py`.

That file only defines the Python class `OpusFile` (like `opus_buffered_encoder.py` defines `OpusBufferedEncoder`).

The actual C-library interface to Opusfile can be found in `opus.py`.  Did you mean for the `Opusfile` and OpenSSL licenses to be inside the file `opus.py`?  That would match the other license locations.

**Comment by Zuzu-Typ** [comment]
@mattgwwalker yupp, that's true. I meant to put it into `opus.py`. Let me fix that real quick...
