### ISSUE TITLE
Error code -133: File couldn't be opened or doesn't exist.

### ISSUE THREAD

**Issue by georgearun** [TeamPyOgg/PyOgg#68]
```
import pyogg

opus_file = pyogg.OpusFile("C:/voice/renamed.opus")
```

I've written the above code to read the opus file but I'm getting the following error "PyOggError: file couldn't be opened or doesn't exist. Error code  -133" even though the file exists.
Is there a solution to this issue?

**Comment by mattgwwalker** [comment]
One possibility is that the opus file is corrupt. Can you play it with the
likes of VLC or Firefox?

OpusFile doesn’t use the standard python file handling facilities. I’m not
a Windows user, but I’d consider trying swapping out the slashes: / for \.

You could try moving the file to the working directory. That would allow
you to refer to the file as just “renamed.opus”. If it still doesn't work,
then it’s probably a corrupt file. If it does work then it’s likely the
slashes or similar that are causing difficulties.

Please report back to tell us how you go.

Cheers,

Matthew

**Comment by mattgwwalker** [comment]
Also, it would be worthwhile trying the examples out. They should work
without error on your machine. That should give you confidence that PyOgg
is installed correctly.

For even more confidence generation, you could also run the tests. They too
should pass without error.

Both the examples and tests check file reading.

Matthew
