### ISSUE TITLE
On Windows, non-ascii path breaks VorbisFile

### ISSUE THREAD

**Issue by tyrylu** [TeamPyOgg/PyOgg#84]
Hello.
When passing a path to VorbisFile and the path contains a non-ascii character, on Windows it results in a -1 error code from the C library. It would seem that vorbisfile and friends do not expect UTF-8 encoded strings, at least not on Windows.

**Comment by mattgwwalker** [comment]
Unfortunately, you're entirely right.  Issue #53 gives you an idea of where we are on this topic.

Would you like to contribute a solution to this issue?  If you're interested, please let us know.

I'll close this issue, but please feel free to continue the discussion on the other thread (#53).

Thanks,

Matthew
