### ISSUE TITLE
Docs: include simple oneliner for apt-get install of common dependencies on Linux

### ISSUE THREAD

**Issue by JRMeyer** [TeamPyOgg/PyOgg#85]
Firstly, thank you for open-sourcing these great tools! 

We're using them do load training data for training Speech-to-Text models at [Coqui STT](https://github.com/coqui-ai/STT) :)

I was using `pyogg` from a script in a new Ubuntu 18.04 environment, I got the following `AttributeError`:

```
AttributeError: module 'pyogg.opus' has no attribute 'op_open_file'
```
Looking through the list of dependencies on [the docs](https://pyogg.readthedocs.io/en/latest/installation.html), it wasn't immediately obvious to me what to install. It turned out the solution was to install [`libopusfile0`](https://launchpad.net/ubuntu/+source/opusfile).

Hindsight is 20-20, and I now see in docs the bulleted list under Linux `OpusFile`. I'd suggest (as with the MacOs example), a simple oneline install command to include for linux. It took me about 30 minutes to figure out what the missing lib was, and for most distros the packages are named similarly enough to make that debugging faster.

**Comment by mattgwwalker** [comment]
Hey Josh,

Thanks for the feedback.

One quick question, did you use the example file
00-test-library-availability? If you didn’t, would that have helped you
debug the problem faster?

Next, if you have any contributions you’d like to make, please feel super
welcome to make a pull request.

Cheers,

Matthew

**Comment by JRMeyer** [comment]
Hi Matthew -- I didn't use `00-test-library-availability`, no. It might have helped debug faster, thanks for pointing it out! I'll close this and if there's a PR I'll send your way. thanks!
